### ISSUE TITLE
Test failure: Precompilation_WorksForPageWithRoute

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/MvcPrecompilation#287] opened 2018-08-23 19:01 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=537575&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
Failed to GET content from /PageWithRoute/Dan. Status code RequestTimeout.
Expected: True
Actual:   False
   at FunctionalTests.HttpClientExtensions.GetStringWithRetryAsync(HttpClient httpClient, String url, ILogger logger) in /_/test/FunctionalTests/Infrastructure/HttpClientExtensions.cs:line 35
   at FunctionalTests.RazorPagesAppTest_CoreCLR.Precompilation_WorksForPageWithRoute() in /_/test/FunctionalTests/CoreCLRTests/RazorPagesAppTest_CoreCLR.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.018s] TestLifetime Information: Starting test Precompilation_WorksForPageWithRoute at 2018-08-23T17:39:50
| [0.002s] TestLifetime Information: Starting test Precompilation_WorksForPageWithRoute at 2018-08-23T17:39:50
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionDirectory=/mnt/work/33bdfc1cae7b2a38/modules/MvcPrecompilation/
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionConfiguration=Release
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "/mnt/temp/buildTmp/366f6caa308146a59c1ab618a9e33291" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.564s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
| [0.564s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [3.254s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   RazorPagesApp -> /mnt/temp/buildTmp/PrecompilationTool/bzetgqpd.vbu/RazorPagesApp/bin/Release/netcoreapp2.2/RazorPagesApp.dll
| [14.929s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   RazorPagesApp -> /mnt/temp/buildTmp/366f6caa308146a59c1ab618a9e33291/
| [15.077s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| [15.077s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /mnt/temp/buildTmp/366f6caa308146a59c1ab618a9e33291/RazorPagesApp.dll --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [15.077s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [15.078s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [15.078s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| [15.078s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionDirectory=/mnt/work/33bdfc1cae7b2a38/modules/MvcPrecompilation/
| [15.078s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET SolutionConfiguration=Release
| [15.096s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 30866
| [17.884s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| [17.886s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /mnt/temp/buildTmp/366f6caa308146a59c1ab618a9e33291
| [17.886s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://127.0.0.1:34729
| [17.886s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [17.886s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://127.0.0.1:34729/
| [17.892s] RazorPagesApp Warning: Retry count 1..
| [18.221s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Server.Kestrel[17]
| [18.221s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Connection id "0HLG93TS3PL0R" bad request data: "Reading the request headers timed out."
| [18.221s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request headers timed out.
| [18.221s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
| [18.221s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
| [18.221s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
| [18.222s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
| [23.1
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-23 19:01
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-23 19:01
Publish_UsesRazorSDK [failed with about the same error](http://aspnetci/viewLog.html?buildId=537534&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-24 17:15
Publish_UsesRazorSDK [failed with about the same error](http://aspnetci/viewLog.html?buildId=538132&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pranavkm** [comment] 2018-08-24 17:45
Yup, I'll go ahead and disable a couple of these these failing ones

**Comment by aspnet-hello** [comment] 2018-08-25 00:12
MvcRazorFilesToCompile_OverridesTheFilesToBeCompiled [failed with about the same error](http://aspnetci/viewLog.html?buildId=538930&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment] 2018-08-27 22:01
Publish_UsesRazorSDK [failed with about the same error](http://aspnetci/viewLog.html?buildId=540067&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pranavkm** [comment] 2018-08-27 22:51
Seems like this was a recent regression in Kestrel. Should be fixed by https://github.com/aspnet/KestrelHttpServer/pull/2851/files, https://github.com/aspnet/KestrelHttpServer/pull/2856/commits/f70ba53253480a0c9b672537b8b13058b3e16160. I'll close this once we can confirm the issues have been resolved.

**Comment by aspnet-hello** [comment] 2018-08-28 02:00
PrecompiledAssembliesUseSameStrongNameAsApplication [failed with about the same error](http://aspnetci/viewLog.html?buildId=540405&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pranavkm** [comment] 2018-09-04 17:00
Looks like the issue was resolved with Kestrel fixes.

**Closed by pranavkm** 2018-09-04 17:00 UTC
Labels: 1 - Ready, Branch:2.2, Branch:master, PRI: 1 - Required, task, test-failure
