### ISSUE TITLE
Stop publishing on view precompilation failed

### ISSUE THREAD

**Issue by AR1ES** [aspnet/MvcPrecompilation#69] opened 2017-01-27 12:52 UTC
Is it possible to prevent publishing on precompilation error and exit with a non-zero exit code?

**Comment by pranavkm** [comment] 2017-01-27 18:11
The issue is specific to scripts in project.json based projects (https://github.com/dotnet/cli/issues/3266). This is fixed once you update to the MsBuild based tooling.

**Closed by pranavkm** 2017-01-27 18:11 UTC
