### ISSUE TITLE
Publish fails with MvcPrecompilation

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/MvcPrecompilation#190] opened 2017-08-20 12:36 UTC
Hello, 

On a website targeting framework `net461` with runtime `win10-x64` using `2.0.0` aspnetcore dependencies the publication fails when we activate MvcPrecompilation.

Publish command : `dotnet publish {PROJECT_PATH} --configuration release -r win10-x64`

Error : 
`C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(97,5): error MSB3030: Could not copy the file "bin\Release\net461\win10-x64\{PROJECT_NAME}.exe.config" because it was not found. [{PROJECT_PATH}\{PROJECT_NAME}.csproj]`

**Comment by pranavkm** [comment] 2017-08-21 18:03
@IsaacSee do you have a repro application for this? I couldn't repro it starting from a template.

**Comment by Eilon** [comment] 2017-09-01 22:59
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-09-01 22:59 UTC
