### ISSUE TITLE
MVC is still looking for .cshtml files

### ISSUE THREAD

**Issue by macgyver76** [aspnet/MvcPrecompilation#107] opened 2017-03-27 10:23 UTC
When executing `Index` action in Area I've got this error:

> An unhandled exception has occurred: The view 'Index' was not found. The following locations were searched

Hovewer actions from `LoginController` are performing fine. I assume reason for this that `LoginController` is not in `Areas`.

 I noticed that `.csproj` MVC View Precompilation is deleting .cshtml files from Views folder (in Areas also). As far as know old `.json` style project didn't do that and before migration everything was working ok. Question is - does old `.cshtml` files need to be in publish output or not (aka where is the bug - in the old or new precompilation system)? 

Here is snippet of my `.csproj` file:
```xml
<PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>xxx</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>xxx</PackageId>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <Version>1.0.0</Version>
    <RuntimeIdentifiers>win7-x86;win81-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Update="wwwroot\**\*;**.cshtml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
```

**Comment by pranavkm** [comment] 2017-03-27 16:28
>  noticed that .csproj MVC View Precompilation is deleting .cshtml files from Views folder (in Areas also)

Is that in the output path or in the actual source directory? The ones in the output directory don't get used and the tool attempts to avoid publishing them. 

1. Does the view get rendered when you have precompilation disabled?
2. If (1) works, does the casing for the file on disk match the casing of the action name? Precompiled view lookups are case sensitive.

**Comment by macgyver76** [comment] 2017-03-28 06:14
> Is that in the output path or in the actual source directory?

I mean output of `dotnet publish` command.

> Does the view get rendered when you have precompilation disabled?

Yes. I disabled this feature in my testing environment and views are getting rendered properly.

> If (1) works, does the casing for the file on disk match the casing of the action name?

Yes. Action is located in base controller. And filename is `Index.cshtml` located in specific Area.

```csharp
public virtual async Task<IActionResult> Index()
{
    var model = GetModel();
    return View(model);
}
```

**Comment by pranavkm** [comment] 2017-03-28 16:05
Could you stick these lines in a controller to print out what views Mvc discovered:

```C#
public string PrintViews([FromServices]ApplicationPartManager manager)
{
  var feature = new ViewsFeature();
  applicationPartManager.PopulateFeature(feature);
  return string.Join("\n", feature.Views.Keys);
}
```

Paste the results here, it might help figuring out what's going on here.

**Comment by macgyver76** [comment] 2017-03-29 06:05
Action `en-us/stock/assortment/printviews` produces a long list of view file names. I don't really want to paste them all here so here is the snippet:

>--omitted--
>/Areas/Stock/Views/Assortment/Index.cshtml
>/Areas/Stock/Views/_ViewImports.cshtml
>--omitted--
>/Views/Account/ConfirmEmail.cshtml
>/Views/Account/Login.cshtml
>/Views/Account/Register.cshtml
>/Views/Account/RegisterCustomer.cshtml
>--omitted--
>/Views/_ViewImports.cshtml
>/Views/_ViewStart.cshtml

**Comment by aqueenan** [comment] 2017-03-31 14:21
`PreserveCompilationContext` gets migrated from the project.json, but doesn't seem to affect view file publishing any more.

Replace `<PreserveCompilationContext>true</PreserveCompilationContext>` with `<MvcRazorExcludeViewFilesFromPublish>false</MvcRazorExcludeViewFilesFromPublish>` and the views will be published as before.

That doesn't solve the underlying problem, but should get you working again. From your description, it sounds as though the view precompiler isn't precompiling the Area view, or the runtime loader can't find the precompiled Area view. Have a look at the assembly in the Object Browser. Does a class for the Area index show up?

Warning: I don't know if MvcRazorExcludeViewFilesFromPublish is an officially supported feature. I figured it out from the [source](https://github.com/aspnet/MvcPrecompilation/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/common.targets#L61#L63), but it isn't mentioned in the release notes, and searching for `MvcRazorExcludeViewFilesFromPublish` on Google returns a total of three identical entries.

**Comment by pranavkm** [comment] 2017-03-31 14:47
@aqueenan - the flag was expressly designed to support publishing views as part of the output. However, the issue here isn't the missing files in the outputs, it's that the precompiled view isn't getting discovered by the view engine.

**Comment by puddlewitt** [comment] 2017-04-04 11:29
I seem to be having a similar issue but the editor templates...

![ohdear](https://cloud.githubusercontent.com/assets/2998294/24654586/2f492dee-1932-11e7-9b79-6220bfaccab4.png)

They are added to the assembly, but the view engine never finds them.

What's the downside of using `MvcRazorExcludeViewFilesFromPublish=false` does this mean the assembly is ignored because the views now physically exist?

**Comment by mrahhal** [comment] 2017-04-29 12:57
I believe this issue is related to #121.

@macgyver76 if the name inside your `AreaAttribute` is lowercased and the folder itself is uppercased then that's probably what's causing the error.

**Comment by pranavkm** [comment] 2017-04-30 18:38
@puddlewitt - we first lookup for precompiled views. If that fails, we fallback to doing runtime compilation (since your application could have a mix of runtime-compiled and precompiled views). In your case, EditorTemplate file names have to match the actual type names (for instance, the file has to be named `DateTime.cshtml`) for the precompiled look up to succeed. 

> What's the downside of using MvcRazorExcludeViewFilesFromPublish=false does this mean the assembly is ignored because the views now physically exist?

Well you're paying the cost of performing runtime compilation. Presumably that's something you want to avoid since you're chosing to precompile views.

@mrahhal - I responded to you in the other work item #121, but essentially this is by design.

**Comment by macgyver76** [comment] 2017-05-10 08:34
@mrahhal There is no `AreaAttribute` in the project hovewer `LowercaseUrls` is enabled. 

```csharp
services.Configure<RouteOptions>(options =>
{
    options.LowercaseUrls = true;
    options.AppendTrailingSlash = false;
});
```

When I change folder name of the area to lowercase precompilation works fine. Otherwise I've got this in log file (you can replace `stock` with any area name, `LanguageViewLocationExpander` enabled):
>System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Areas/stock/Views/Assortment/Index.en-US.en-US.cshtml
/Areas/stock/Views/Assortment/Index.en.en-US.cshtml
/Areas/stock/Views/Assortment/Index.en-US.cshtml
/Areas/stock/Views/Assortment/Index.en-US.en.cshtml
/Areas/stock/Views/Assortment/Index.en.us.cshtml
/Areas/stock/Views/Assortment/Index.en.cshtml
/Areas/stock/Views/Assortment/Index.en-US.cshtml
/Areas/stock/Views/Assortment/Index.en.cshtml
/Areas/stock/Views/Assortment/Index.cshtml
/Areas/stock/Views/Shared/Index.en-US.en-US.cshtml
/Areas/stock/Views/Shared/Index.en.en-US.cshtml
/Areas/stock/Views/Shared/Index.en-US.cshtml
/Areas/stock/Views/Shared/Index.en-US.en.cshtml
/Areas/stock/Views/Shared/Index.en.en.cshtml
/Areas/stock/Views/Shared/Index.en.cshtml
/Areas/stock/Views/Shared/Index.en-US.cshtml
/Areas/stock/Views/Shared/Index.en.cshtml
/Areas/stock/Views/Shared/Index.cshtml
/Views/Shared/Index.en-US.en-US.cshtml
/Views/Shared/Index.en.en-US.cshtml
/Views/Shared/Index.en-US.cshtml
/Views/Shared/Index.en-US.en.cshtml
/Views/Shared/Index.en.us.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.en-US.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.cshtml

**Comment by pranavkm** [comment] 2017-05-10 15:58
@macgyver76 - here's what I gather from your description

* Your area is named `Stock` (with a upper case "S")
* The folder hierarchy is `Areas/Stock/Views` (with a upper case "S")

With view precompilation enabled, the lookup fails until you change the area name to `stock` with a lower case "S". Does that sound right?

**Comment by macgyver76** [comment] 2017-05-11 05:01
@pranavkm - Yup.

**Comment by Eilon** [comment] 2017-06-19 16:36
@pranavkm can you verify if this is already fixed by the other casing fix you did?

**Comment by pranavkm** [comment] 2017-06-20 15:14
Yup, looks like this was fixed as part of addressing https://github.com/aspnet/MvcPrecompilation/issues/37. @macgyver76, could you give this a try either with our nightlies (`https://dotnet.myget.org/gallery/aspnetcore-release`) or wait a few days for preview2 to be released to verify this? Feel free to reopen if you're still running in to this issue.

**Closed by pranavkm** 2017-06-20 15:14 UTC

**Comment by macgyver76** [comment] 2017-06-21 10:14
@pranavkm I'll get you know after migrating our project to stable version of `aspnet`.

**Comment by macgyver76** [comment] 2017-08-22 08:57
@pranavkm As far as I know, view precompilation works fine after upgrading to 2.0.
