### ISSUE TITLE
Print an error when MvcRazorFilesToCompile is empty

### ISSUE THREAD

**Issue by guylando** [aspnet/MvcPrecompilation#87] opened 2017-02-17 11:55 UTC
I added the precompilation package and csproj tag and when I publish the main project I get the error:

```
bin\Release\net451\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.exe @"obj\Release\net451\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"
EXEC(6,49): Error CS0826: No best type found for implicitly-typed array
EXEC(6,49): Error CS1503: Argument 1: cannot convert from '?[]' to 'System.Collections.Generic.IReadOnlyList<Microsoft.AspNetCore.Mvc.ApplicationParts.ViewInfo>'
C:\Users\XXX\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0-msbuild4-final\build\net451\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(36,5): Error MSB3073: The command "bin\Release\net451\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.exe @"obj\Release\net451\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1.
```

I have a solution with a couple of projects where the views are separated to a different project than the main project. Does the views precompilation supports such a situation? Is this related to the error?
Do you recognize this error or encountered it before and have a workaround?

**Comment by Eilon** [comment] 2017-02-28 18:17
Hi @guylando , I think that the scenario you describe should work.

Can you please share your project, or at least the relevant parts of your csproj file? Also, if you can share the generated `obj\Release\net451\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp` file that would help as well.

**Comment by Eilon** [comment] 2017-03-09 18:21
Closing because we don't have enough information to reproduce.

**Comment by henkmollema** [comment] 2017-03-10 10:02
@Eilon I'm running into this issue too since I've migrated to MSBuild. It worked using the project.json.

I have a class library with views which I want to precompile and embed into the assembly to consume them in multiple applications. This scenario is similar to what is begin tested in this repo with these projects: 
[ClassLibraryWithPrecompiledViews](https://github.com/aspnet/MvcPrecompilation/tree/b57d8079ff3425a77ee15e94e95d5c860bb3d3d0/testapps/ClassLibraryWithPrecompiledViews) and [ApplicationUsingPrecompiledViewClassLibrary](https://github.com/aspnet/MvcPrecompilation/tree/b57d8079ff3425a77ee15e94e95d5c860bb3d3d0/testapps/ApplicationUsingPrecompiledViewClassLibrary).

The csproj of my class library looks like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>

    <PreserveCompilationContext>true</PreserveCompilationContext>
    <OutputType>Exe</OutputType>
    <MvcRazorOutputPath Condition="'$(TargetFramework)'!=''">obj\precompiled\$(TargetFramework)</MvcRazorOutputPath>    
  </PropertyGroup>

  <ItemGroup>
    <Content Include="obj\precompiled\**\*" Pack="true" PackagePath="lib\%(RecursiveDir)%(FileName)%(Extension)" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0" PrivateAssets="All" />
  </ItemGroup>

  <Target Name="PrecompileRazorViews" AfterTargets="Build" DependsOnTargets="MvcRazorPrecompile" Condition="'$(TargetFramework)'!=''" />
</Project>
```

When I call `dotnet build` on this project I receive the same error as @guylando. Except for that fact that I'm using a `.netcoreapp1.1` target framework, the error is the same.

My `microsoft.aspnetcore.mvc.razor.viewcompilation.rsp` file:
```
C:\src\App\src\MyTemplatesApp
--output-path=obj\precompiled\netcoreapp1.1\
--application-name=MyTemplatesApp
--content-root=C:\src\App\src\MyTemplatesApp
--file=
```

.NET Core version:
```
λ dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by henkmollema** [comment] 2017-03-10 10:08
I was thinking, does the 1.1 runtime packages of this even work with MSBuild tooling?

**Comment by henkmollema** [comment] 2017-03-10 10:13
I guess the problem is that the `--file=` part is empty. My templates are in this folder structure (starting from the root):
```
/Templates
  /Controls
    /Textbox.cshtml
    /Dropdown.cshtml
  /SomeOtherTemplate.cshtml
```

**Comment by henkmollema** [comment] 2017-03-10 11:08
@Eilon @guylando I guess I found the issue. When I use the Web SDK it seems to work:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

Perhaps there is some magic in there that makes  this work.

**Comment by pranavkm** [comment] 2017-03-10 12:46
@henkmollema  Thanks for looking in to this at depth. The `Microsoft.Net.Sdk.Web` marks cshtml files as [`Compile`](https://github.com/aspnet/websdk/blob/dev/src/Web/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L29) which is what we look for 
https://github.com/aspnet/MvcPrecompilation/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/common.targets#L15. 

@Eilon, we should fail more gracefully when we can't find any cshtml files to compile. Let's use this work item to track it.

**Comment by henkmollema** [comment] 2017-03-10 15:38
Thanks @pranavkm. That makes sense.

**Comment by Eilon** [comment] 2017-03-10 17:42
Is it actually an error to have no CSHTML files? Perhaps a warning would make more sense?

**Comment by Eilon** [comment] 2017-03-10 17:42
cc @DamianEdwards for thoughts.

**Comment by pranavkm** [comment] 2017-03-10 17:44
> Perhaps a warning would make more sense?
Yeah, that would be fine. 

*Precompilation is enabled, but no cshtml files were found. Set `...` in your project to specify the views to compile.*

**Comment by Eilon** [comment] 2017-06-14 22:07
@ajaybhargavb / @pranavkm - @danroth27 just tried publishing a new default Web API project with 2.0 and didn't see any error/warning/anything. Was this maybe fixed by some other change in recent history?

**Comment by pranavkm** [comment] 2017-06-14 23:54
Wouldn't we want to print a warning though (at least that's what I assumed we wanted to do here)

**Comment by Eilon** [comment] 2017-06-15 00:19
When @danroth27 and I were talking, we were wondering if the correct behavior is to be silent. What exactly would we be warning the user about? What would they "fix" to avoid this?

Imagine a pure Web API project, which of course has no views, but also has view pre-compilation enabled (because it's enabled by the SDK by default). It doesn't make sense to have a warning in that case, does it?

**Comment by pranavkm** [comment] 2017-06-15 00:38
I guess that makes sense. Perhaps it's best to get some more feedback to see if it's something people keep running in to and decide accordingly (maybe an MSBuild info log or something along those lines).

**Comment by Eilon** [comment] 2017-06-15 00:40
So are we good to close this for now? No warnings/errors are ever shown?

**Comment by guylando** [comment] 2017-06-15 05:57
The problem in my case might have been that the sdk of the views project was Microsoft.Net instead of Microsoft.Net.Web.
It also caused the visual studio razor intellisense to not work in the views. Had no warning or anything so discovered it by luck. I encounter too many times such cases where I search the problem with procmon myself because of no warnings and no online info. For example visual studio "run code analysis" missing for big files and no info about that anywhere or anything about where can I configure file size limitation.

**Comment by Eilon** [comment] 2017-06-16 16:01
@pranavkm - can you confirm that's what you're seeing on the latest `dev` bits?

**Comment by pranavkm** [comment] 2017-06-20 18:39
Verified this no longer prints an error. We produce a `<App Name>.PrecompiledViews.dll`, but it's empty. No runtime exceptions either, so this should be good to close.

**Closed by pranavkm** 2017-06-20 18:39 UTC
Labels: 1 - Ready, bug
